### ISSUE TITLE
[Refactor] 1주차 금요일 리뷰 반영

### ISSUE THREAD

**Issue by fivethreeeo** [KTH-96/issue-tracker#21]
- [x] ts-loader를 babel-loader로 변경 (1주차 수요일 리뷰 반영)
- [x] 공통 컴포넌트의 props를 네이티브 attributes 모양으로 통일 (Button, TextInput 등)
- [x] Or 태그 수정
- [ ] webpack devtool source-map 설정 고민, 수정
- [x] LoginPage 컴포넌트에서 페이지를 구성하는 컴포넌트 분리
- [x] idRef 조건 체크하는 부분 수정

**Comment by ppamppamman** [comment]
안녕하세요 빰빰입니다 레포지토리에 놀러왔는데 잘못이해하고 있는 부분이 있어서 바로잡으려구요!

> LoginPage 컴포넌트에서 페이지를 구성하는 컴포넌트 분리

이 부분은 적힌 거만 봐서는 약간 잘못 이해를 하신건 아닌가 하는데 혹시 오늘 잠깐 슬랙을 해볼 수 있을까요??
