### ISSUE TITLE
2주차 금요일 리뷰 반영

### ISSUE THREAD

**Issue by nanjeong** [KTH-96/issue-tracker#38]
### Description
- 2주차 금요일 리뷰 반영한다.

### Tasks
- [ ] 필터 바 부분 옐로우가 리뷰 반영
- [ ] 이슈 목록 부분 난정이 리뷰 반영

**Comment by nanjeong** [comment]
난정
- 예상 시간: 1시간 30분

**Comment by fivethreeeo** [comment]
옐로우
- 예상시간: 1시간

**Comment by nanjeong** [comment]
난정
- 실제 작업 시간: 5시간 (예상시간 + 3시간 30분)
- useState로 관리하던 체크 상태를 useReducer로 변경
- useReducer와 context api에 typescript를 처음 적용해서 시간이 많이 소요됨
