### ISSUE TITLE
Theme 설정

### ISSUE THREAD

**Issue by nanjeong** [KTH-96/issue-tracker#8]
### Description

- 폰트, 색상, 아이콘을 설정한다.

### Tasks

- [x] 폰트 설정
- [x] 색상 설정
- [x] 아이콘 설정

**Comment by fivethreeeo** [comment]
작업 계획
- 예상 작업 시간: 1시간 20분

**Comment by fivethreeeo** [comment]
작업 리뷰
- 작업 소요 시간: 2시간 30분
- 1시간 10분 더 소요

회고
- Icon을 svgr를 사용해서 컴포넌트처럼 사용하는 방식을 새롭게 도입
- 절대 경로 설정 실패(나중에 다시 시도하기로)
- 절대경로 설정하는 과정에서 시간이 예상보다 오래 걸림
